
package com.vaadin.prototype.wc.gwt.client.html;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.js.JsProperty;
import com.google.gwt.core.client.js.JsType;

@JsType(prototype = "CSSStyleDeclaration", isNative = true)
public interface HTMLStyle {
  String getPropertyValue();
  int getPropertyPriority();
  void setProperty(String prop, String val);
  void removeProperty(String prop);
  JavaScriptObject getPropertyCSSValue();
  @JsProperty String cssText();
  @JsProperty HTMLStyle cssText(String arg);
  @JsProperty String alignContent();
  @JsProperty HTMLStyle alignContent(String arg);
  @JsProperty String alignItems();
  @JsProperty HTMLStyle alignItems(String arg);
  @JsProperty String alignSelf();
  @JsProperty HTMLStyle alignSelf(String arg);
  @JsProperty String alignmentBaseline();
  @JsProperty HTMLStyle alignmentBaseline(String arg);
  @JsProperty String backfaceVisibility();
  @JsProperty HTMLStyle backfaceVisibility(String arg);
  @JsProperty String background();
  @JsProperty HTMLStyle background(String arg);
  @JsProperty String backgroundAttachment();
  @JsProperty HTMLStyle backgroundAttachment(String arg);
  @JsProperty String backgroundBlendMode();
  @JsProperty HTMLStyle backgroundBlendMode(String arg);
  @JsProperty String backgroundClip();
  @JsProperty HTMLStyle backgroundClip(String arg);
  @JsProperty String backgroundColor();
  @JsProperty HTMLStyle backgroundColor(String arg);
  @JsProperty String backgroundImage();
  @JsProperty HTMLStyle backgroundImage(String arg);
  @JsProperty String backgroundOrigin();
  @JsProperty HTMLStyle backgroundOrigin(String arg);
  @JsProperty String backgroundPosition();
  @JsProperty HTMLStyle backgroundPosition(String arg);
  @JsProperty String backgroundPositionX();
  @JsProperty HTMLStyle backgroundPositionX(String arg);
  @JsProperty String backgroundPositionY();
  @JsProperty HTMLStyle backgroundPositionY(String arg);
  @JsProperty String backgroundRepeat();
  @JsProperty HTMLStyle backgroundRepeat(String arg);
  @JsProperty String backgroundRepeatX();
  @JsProperty HTMLStyle backgroundRepeatX(String arg);
  @JsProperty String backgroundRepeatY();
  @JsProperty HTMLStyle backgroundRepeatY(String arg);
  @JsProperty String backgroundSize();
  @JsProperty HTMLStyle backgroundSize(String arg);
  @JsProperty String baselineShift();
  @JsProperty HTMLStyle baselineShift(String arg);
  @JsProperty String border();
  @JsProperty HTMLStyle border(String arg);
  @JsProperty String borderBottom();
  @JsProperty HTMLStyle borderBottom(String arg);
  @JsProperty String borderBottomColor();
  @JsProperty HTMLStyle borderBottomColor(String arg);
  @JsProperty String borderBottomLeftRadius();
  @JsProperty HTMLStyle borderBottomLeftRadius(String arg);
  @JsProperty String borderBottomRightRadius();
  @JsProperty HTMLStyle borderBottomRightRadius(String arg);
  @JsProperty String borderBottomStyle();
  @JsProperty HTMLStyle borderBottomStyle(String arg);
  @JsProperty String borderBottomWidth();
  @JsProperty HTMLStyle borderBottomWidth(String arg);
  @JsProperty String borderCollapse();
  @JsProperty HTMLStyle borderCollapse(String arg);
  @JsProperty String borderColor();
  @JsProperty HTMLStyle borderColor(String arg);
  @JsProperty String borderImage();
  @JsProperty HTMLStyle borderImage(String arg);
  @JsProperty String borderImageOutset();
  @JsProperty HTMLStyle borderImageOutset(String arg);
  @JsProperty String borderImageRepeat();
  @JsProperty HTMLStyle borderImageRepeat(String arg);
  @JsProperty String borderImageSlice();
  @JsProperty HTMLStyle borderImageSlice(String arg);
  @JsProperty String borderImageSource();
  @JsProperty HTMLStyle borderImageSource(String arg);
  @JsProperty String borderImageWidth();
  @JsProperty HTMLStyle borderImageWidth(String arg);
  @JsProperty String borderLeft();
  @JsProperty HTMLStyle borderLeft(String arg);
  @JsProperty String borderLeftColor();
  @JsProperty HTMLStyle borderLeftColor(String arg);
  @JsProperty String borderLeftStyle();
  @JsProperty HTMLStyle borderLeftStyle(String arg);
  @JsProperty String borderLeftWidth();
  @JsProperty HTMLStyle borderLeftWidth(String arg);
  @JsProperty String borderRadius();
  @JsProperty HTMLStyle borderRadius(String arg);
  @JsProperty String borderRight();
  @JsProperty HTMLStyle borderRight(String arg);
  @JsProperty String borderRightColor();
  @JsProperty HTMLStyle borderRightColor(String arg);
  @JsProperty String borderRightStyle();
  @JsProperty HTMLStyle borderRightStyle(String arg);
  @JsProperty String borderRightWidth();
  @JsProperty HTMLStyle borderRightWidth(String arg);
  @JsProperty String borderSpacing();
  @JsProperty HTMLStyle borderSpacing(String arg);
  @JsProperty String borderStyle();
  @JsProperty HTMLStyle borderStyle(String arg);
  @JsProperty String borderTop();
  @JsProperty HTMLStyle borderTop(String arg);
  @JsProperty String borderTopColor();
  @JsProperty HTMLStyle borderTopColor(String arg);
  @JsProperty String borderTopLeftRadius();
  @JsProperty HTMLStyle borderTopLeftRadius(String arg);
  @JsProperty String borderTopRightRadius();
  @JsProperty HTMLStyle borderTopRightRadius(String arg);
  @JsProperty String borderTopStyle();
  @JsProperty HTMLStyle borderTopStyle(String arg);
  @JsProperty String borderTopWidth();
  @JsProperty HTMLStyle borderTopWidth(String arg);
  @JsProperty String borderWidth();
  @JsProperty HTMLStyle borderWidth(String arg);
  @JsProperty String bottom();
  @JsProperty HTMLStyle bottom(String arg);
  @JsProperty String boxShadow();
  @JsProperty HTMLStyle boxShadow(String arg);
  @JsProperty String boxSizing();
  @JsProperty HTMLStyle boxSizing(String arg);
  @JsProperty String bufferedRendering();
  @JsProperty HTMLStyle bufferedRendering(String arg);
  @JsProperty String captionSide();
  @JsProperty HTMLStyle captionSide(String arg);
  @JsProperty String clear();
  @JsProperty HTMLStyle clear(String arg);
  @JsProperty String clip();
  @JsProperty HTMLStyle clip(String arg);
  @JsProperty String clipPath();
  @JsProperty HTMLStyle clipPath(String arg);
  @JsProperty String clipRule();
  @JsProperty HTMLStyle clipRule(String arg);
  @JsProperty String color();
  @JsProperty HTMLStyle color(String arg);
  @JsProperty String colorInterpolation();
  @JsProperty HTMLStyle colorInterpolation(String arg);
  @JsProperty String colorInterpolationFilters();
  @JsProperty HTMLStyle colorInterpolationFilters(String arg);
  @JsProperty String colorRendering();
  @JsProperty HTMLStyle colorRendering(String arg);
  @JsProperty String content();
  @JsProperty HTMLStyle content(String arg);
  @JsProperty String counterIncrement();
  @JsProperty HTMLStyle counterIncrement(String arg);
  @JsProperty String counterReset();
  @JsProperty HTMLStyle counterReset(String arg);
  @JsProperty String cursor();
  @JsProperty HTMLStyle cursor(String arg);
  @JsProperty String direction();
  @JsProperty HTMLStyle direction(String arg);
  @JsProperty String display();
  @JsProperty HTMLStyle display(String arg);
  @JsProperty String dominantBaseline();
  @JsProperty HTMLStyle dominantBaseline(String arg);
  @JsProperty String emptyCells();
  @JsProperty HTMLStyle emptyCells(String arg);
  @JsProperty String enableBackground();
  @JsProperty HTMLStyle enableBackground(String arg);
  @JsProperty String fill();
  @JsProperty HTMLStyle fill(String arg);
  @JsProperty String fillOpacity();
  @JsProperty HTMLStyle fillOpacity(String arg);
  @JsProperty String fillRule();
  @JsProperty HTMLStyle fillRule(String arg);
  @JsProperty String filter();
  @JsProperty HTMLStyle filter(String arg);
  @JsProperty String flex();
  @JsProperty HTMLStyle flex(String arg);
  @JsProperty String flexBasis();
  @JsProperty HTMLStyle flexBasis(String arg);
  @JsProperty String flexDirection();
  @JsProperty HTMLStyle flexDirection(String arg);
  @JsProperty String flexFlow();
  @JsProperty HTMLStyle flexFlow(String arg);
  @JsProperty String flexGrow();
  @JsProperty HTMLStyle flexGrow(String arg);
  @JsProperty String flexShrink();
  @JsProperty HTMLStyle flexShrink(String arg);
  @JsProperty String flexWrap();
  @JsProperty HTMLStyle flexWrap(String arg);
  @JsProperty String getFloat();
  @JsProperty HTMLStyle setFloat(String arg);
  @JsProperty String floodColor();
  @JsProperty HTMLStyle floodColor(String arg);
  @JsProperty String floodOpacity();
  @JsProperty HTMLStyle floodOpacity(String arg);
  @JsProperty String font();
  @JsProperty HTMLStyle font(String arg);
  @JsProperty String fontFamily();
  @JsProperty HTMLStyle fontFamily(String arg);
  @JsProperty String fontKerning();
  @JsProperty HTMLStyle fontKerning(String arg);
  @JsProperty String fontSize();
  @JsProperty HTMLStyle fontSize(String arg);
  @JsProperty String fontStretch();
  @JsProperty HTMLStyle fontStretch(String arg);
  @JsProperty String fontStyle();
  @JsProperty HTMLStyle fontStyle(String arg);
  @JsProperty String fontVariant();
  @JsProperty HTMLStyle fontVariant(String arg);
  @JsProperty String fontVariantLigatures();
  @JsProperty HTMLStyle fontVariantLigatures(String arg);
  @JsProperty String fontWeight();
  @JsProperty HTMLStyle fontWeight(String arg);
  @JsProperty String glyphOrientationHorizontal();
  @JsProperty HTMLStyle glyphOrientationHorizontal(String arg);
  @JsProperty String glyphOrientationVertical();
  @JsProperty HTMLStyle glyphOrientationVertical(String arg);
  @JsProperty String height();
  @JsProperty HTMLStyle height(String arg);
  @JsProperty String imageRendering();
  @JsProperty HTMLStyle imageRendering(String arg);
  @JsProperty String justifyContent();
  @JsProperty HTMLStyle justifyContent(String arg);
  @JsProperty String left();
  @JsProperty HTMLStyle left(String arg);
  @JsProperty String letterSpacing();
  @JsProperty HTMLStyle letterSpacing(String arg);
  @JsProperty String lightingColor();
  @JsProperty HTMLStyle lightingColor(String arg);
  @JsProperty String lineHeight();
  @JsProperty HTMLStyle lineHeight(String arg);
  @JsProperty String listStyle();
  @JsProperty HTMLStyle listStyle(String arg);
  @JsProperty String listStyleImage();
  @JsProperty HTMLStyle listStyleImage(String arg);
  @JsProperty String listStylePosition();
  @JsProperty HTMLStyle listStylePosition(String arg);
  @JsProperty String listStyleType();
  @JsProperty HTMLStyle listStyleType(String arg);
  @JsProperty String margin();
  @JsProperty HTMLStyle margin(String arg);
  @JsProperty String marginBottom();
  @JsProperty HTMLStyle marginBottom(String arg);
  @JsProperty String marginLeft();
  @JsProperty HTMLStyle marginLeft(String arg);
  @JsProperty String marginRight();
  @JsProperty HTMLStyle marginRight(String arg);
  @JsProperty String marginTop();
  @JsProperty HTMLStyle marginTop(String arg);
  @JsProperty String marker();
  @JsProperty HTMLStyle marker(String arg);
  @JsProperty String markerEnd();
  @JsProperty HTMLStyle markerEnd(String arg);
  @JsProperty String markerMid();
  @JsProperty HTMLStyle markerMid(String arg);
  @JsProperty String markerStart();
  @JsProperty HTMLStyle markerStart(String arg);
  @JsProperty String mask();
  @JsProperty HTMLStyle mask(String arg);
  @JsProperty String maskType();
  @JsProperty HTMLStyle maskType(String arg);
  @JsProperty String maxHeight();
  @JsProperty HTMLStyle maxHeight(String arg);
  @JsProperty String maxWidth();
  @JsProperty HTMLStyle maxWidth(String arg);
  @JsProperty String maxZoom();
  @JsProperty HTMLStyle maxZoom(String arg);
  @JsProperty String minHeight();
  @JsProperty HTMLStyle minHeight(String arg);
  @JsProperty String minWidth();
  @JsProperty HTMLStyle minWidth(String arg);
  @JsProperty String minZoom();
  @JsProperty HTMLStyle minZoom(String arg);
  @JsProperty String objectFit();
  @JsProperty HTMLStyle objectFit(String arg);
  @JsProperty String objectPosition();
  @JsProperty HTMLStyle objectPosition(String arg);
  @JsProperty String opacity();
  @JsProperty HTMLStyle opacity(String arg);
  @JsProperty String order();
  @JsProperty HTMLStyle order(String arg);
  @JsProperty String orientation();
  @JsProperty HTMLStyle orientation(String arg);
  @JsProperty String orphans();
  @JsProperty HTMLStyle orphans(String arg);
  @JsProperty String outline();
  @JsProperty HTMLStyle outline(String arg);
  @JsProperty String outlineColor();
  @JsProperty HTMLStyle outlineColor(String arg);
  @JsProperty String outlineOffset();
  @JsProperty HTMLStyle outlineOffset(String arg);
  @JsProperty String outlineStyle();
  @JsProperty HTMLStyle outlineStyle(String arg);
  @JsProperty String outlineWidth();
  @JsProperty HTMLStyle outlineWidth(String arg);
  @JsProperty String overflow();
  @JsProperty HTMLStyle overflow(String arg);
  @JsProperty String overflowWrap();
  @JsProperty HTMLStyle overflowWrap(String arg);
  @JsProperty String overflowX();
  @JsProperty HTMLStyle overflowX(String arg);
  @JsProperty String overflowY();
  @JsProperty HTMLStyle overflowY(String arg);
  @JsProperty String padding();
  @JsProperty HTMLStyle padding(String arg);
  @JsProperty String paddingBottom();
  @JsProperty HTMLStyle paddingBottom(String arg);
  @JsProperty String paddingLeft();
  @JsProperty HTMLStyle paddingLeft(String arg);
  @JsProperty String paddingRight();
  @JsProperty HTMLStyle paddingRight(String arg);
  @JsProperty String paddingTop();
  @JsProperty HTMLStyle paddingTop(String arg);
  @JsProperty String page();
  @JsProperty HTMLStyle page(String arg);
  @JsProperty String pageBreakAfter();
  @JsProperty HTMLStyle pageBreakAfter(String arg);
  @JsProperty String pageBreakBefore();
  @JsProperty HTMLStyle pageBreakBefore(String arg);
  @JsProperty String pageBreakInside();
  @JsProperty HTMLStyle pageBreakInside(String arg);
  @JsProperty String paintOrder();
  @JsProperty HTMLStyle paintOrder(String arg);
  @JsProperty String perspective();
  @JsProperty HTMLStyle perspective(String arg);
  @JsProperty String perspectiveOrigin();
  @JsProperty HTMLStyle perspectiveOrigin(String arg);
  @JsProperty String pointerEvents();
  @JsProperty HTMLStyle pointerEvents(String arg);
  @JsProperty String position();
  @JsProperty HTMLStyle position(String arg);
  @JsProperty String quotes();
  @JsProperty HTMLStyle quotes(String arg);
  @JsProperty String resize();
  @JsProperty HTMLStyle resize(String arg);
  @JsProperty String right();
  @JsProperty HTMLStyle right(String arg);
  @JsProperty String shapeImageThreshold();
  @JsProperty HTMLStyle shapeImageThreshold(String arg);
  @JsProperty String shapeMargin();
  @JsProperty HTMLStyle shapeMargin(String arg);
  @JsProperty String shapeOutside();
  @JsProperty HTMLStyle shapeOutside(String arg);
  @JsProperty String shapeRendering();
  @JsProperty HTMLStyle shapeRendering(String arg);
  @JsProperty String size();
  @JsProperty HTMLStyle size(String arg);
  @JsProperty String speak();
  @JsProperty HTMLStyle speak(String arg);
  @JsProperty String src();
  @JsProperty HTMLStyle src(String arg);
  @JsProperty String stopColor();
  @JsProperty HTMLStyle stopColor(String arg);
  @JsProperty String stopOpacity();
  @JsProperty HTMLStyle stopOpacity(String arg);
  @JsProperty String stroke();
  @JsProperty HTMLStyle stroke(String arg);
  @JsProperty String strokeDasharray();
  @JsProperty HTMLStyle strokeDasharray(String arg);
  @JsProperty String strokeDashoffset();
  @JsProperty HTMLStyle strokeDashoffset(String arg);
  @JsProperty String strokeLinecap();
  @JsProperty HTMLStyle strokeLinecap(String arg);
  @JsProperty String strokeLinejoin();
  @JsProperty HTMLStyle strokeLinejoin(String arg);
  @JsProperty String strokeMiterlimit();
  @JsProperty HTMLStyle strokeMiterlimit(String arg);
  @JsProperty String strokeOpacity();
  @JsProperty HTMLStyle strokeOpacity(String arg);
  @JsProperty String strokeWidth();
  @JsProperty HTMLStyle strokeWidth(String arg);
  @JsProperty String tabSize();
  @JsProperty HTMLStyle tabSize(String arg);
  @JsProperty String tableLayout();
  @JsProperty HTMLStyle tableLayout(String arg);
  @JsProperty String textAlign();
  @JsProperty HTMLStyle textAlign(String arg);
  @JsProperty String textAnchor();
  @JsProperty HTMLStyle textAnchor(String arg);
  @JsProperty String textDecoration();
  @JsProperty HTMLStyle textDecoration(String arg);
  @JsProperty String textIndent();
  @JsProperty HTMLStyle textIndent(String arg);
  @JsProperty String textLineThroughColor();
  @JsProperty HTMLStyle textLineThroughColor(String arg);
  @JsProperty String textLineThroughMode();
  @JsProperty HTMLStyle textLineThroughMode(String arg);
  @JsProperty String textLineThroughStyle();
  @JsProperty HTMLStyle textLineThroughStyle(String arg);
  @JsProperty String textLineThroughWidth();
  @JsProperty HTMLStyle textLineThroughWidth(String arg);
  @JsProperty String textOverflow();
  @JsProperty HTMLStyle textOverflow(String arg);
  @JsProperty String textOverlineColor();
  @JsProperty HTMLStyle textOverlineColor(String arg);
  @JsProperty String textOverlineMode();
  @JsProperty HTMLStyle textOverlineMode(String arg);
  @JsProperty String textOverlineStyle();
  @JsProperty HTMLStyle textOverlineStyle(String arg);
  @JsProperty String textOverlineWidth();
  @JsProperty HTMLStyle textOverlineWidth(String arg);
  @JsProperty String textRendering();
  @JsProperty HTMLStyle textRendering(String arg);
  @JsProperty String textShadow();
  @JsProperty HTMLStyle textShadow(String arg);
  @JsProperty String textTransform();
  @JsProperty HTMLStyle textTransform(String arg);
  @JsProperty String textUnderlineColor();
  @JsProperty HTMLStyle textUnderlineColor(String arg);
  @JsProperty String textUnderlineMode();
  @JsProperty HTMLStyle textUnderlineMode(String arg);
  @JsProperty String textUnderlineStyle();
  @JsProperty HTMLStyle textUnderlineStyle(String arg);
  @JsProperty String textUnderlineWidth();
  @JsProperty HTMLStyle textUnderlineWidth(String arg);
  @JsProperty String top();
  @JsProperty HTMLStyle top(String arg);
  @JsProperty String touchAction();
  @JsProperty HTMLStyle touchAction(String arg);
  @JsProperty String transform();
  @JsProperty HTMLStyle transform(String arg);
  @JsProperty String transformOrigin();
  @JsProperty HTMLStyle transformOrigin(String arg);
  @JsProperty String transformStyle();
  @JsProperty HTMLStyle transformStyle(String arg);
  @JsProperty String transition();
  @JsProperty HTMLStyle transition(String arg);
  @JsProperty String transitionDelay();
  @JsProperty HTMLStyle transitionDelay(String arg);
  @JsProperty String transitionDuration();
  @JsProperty HTMLStyle transitionDuration(String arg);
  @JsProperty String transitionProperty();
  @JsProperty HTMLStyle transitionProperty(String arg);
  @JsProperty String transitionTimingFunction();
  @JsProperty HTMLStyle transitionTimingFunction(String arg);
  @JsProperty String unicodeBidi();
  @JsProperty HTMLStyle unicodeBidi(String arg);
  @JsProperty String unicodeRange();
  @JsProperty HTMLStyle unicodeRange(String arg);
  @JsProperty String userZoom();
  @JsProperty HTMLStyle userZoom(String arg);
  @JsProperty String vectorEffect();
  @JsProperty HTMLStyle vectorEffect(String arg);
  @JsProperty String verticalAlign();
  @JsProperty HTMLStyle verticalAlign(String arg);
  @JsProperty String visibility();
  @JsProperty HTMLStyle visibility(String arg);
  @JsProperty String webkitAnimation();
  @JsProperty HTMLStyle webkitAnimation(String arg);
  @JsProperty String webkitAnimationDelay();
  @JsProperty HTMLStyle webkitAnimationDelay(String arg);
  @JsProperty String webkitAnimationDirection();
  @JsProperty HTMLStyle webkitAnimationDirection(String arg);
  @JsProperty String webkitAnimationDuration();
  @JsProperty HTMLStyle webkitAnimationDuration(String arg);
  @JsProperty String webkitAnimationFillMode();
  @JsProperty HTMLStyle webkitAnimationFillMode(String arg);
  @JsProperty String webkitAnimationIterationCount();
  @JsProperty HTMLStyle webkitAnimationIterationCount(String arg);
  @JsProperty String webkitAnimationName();
  @JsProperty HTMLStyle webkitAnimationName(String arg);
  @JsProperty String webkitAnimationPlayState();
  @JsProperty HTMLStyle webkitAnimationPlayState(String arg);
  @JsProperty String webkitAnimationTimingFunction();
  @JsProperty HTMLStyle webkitAnimationTimingFunction(String arg);
  @JsProperty String webkitAppRegion();
  @JsProperty HTMLStyle webkitAppRegion(String arg);
  @JsProperty String webkitAppearance();
  @JsProperty HTMLStyle webkitAppearance(String arg);
  @JsProperty String webkitAspectRatio();
  @JsProperty HTMLStyle webkitAspectRatio(String arg);
  @JsProperty String webkitBackfaceVisibility();
  @JsProperty HTMLStyle webkitBackfaceVisibility(String arg);
  @JsProperty String webkitBackgroundClip();
  @JsProperty HTMLStyle webkitBackgroundClip(String arg);
  @JsProperty String webkitBackgroundComposite();
  @JsProperty HTMLStyle webkitBackgroundComposite(String arg);
  @JsProperty String webkitBackgroundOrigin();
  @JsProperty HTMLStyle webkitBackgroundOrigin(String arg);
  @JsProperty String webkitBackgroundSize();
  @JsProperty HTMLStyle webkitBackgroundSize(String arg);
  @JsProperty String webkitBorderAfter();
  @JsProperty HTMLStyle webkitBorderAfter(String arg);
  @JsProperty String webkitBorderAfterColor();
  @JsProperty HTMLStyle webkitBorderAfterColor(String arg);
  @JsProperty String webkitBorderAfterStyle();
  @JsProperty HTMLStyle webkitBorderAfterStyle(String arg);
  @JsProperty String webkitBorderAfterWidth();
  @JsProperty HTMLStyle webkitBorderAfterWidth(String arg);
  @JsProperty String webkitBorderBefore();
  @JsProperty HTMLStyle webkitBorderBefore(String arg);
  @JsProperty String webkitBorderBeforeColor();
  @JsProperty HTMLStyle webkitBorderBeforeColor(String arg);
  @JsProperty String webkitBorderBeforeStyle();
  @JsProperty HTMLStyle webkitBorderBeforeStyle(String arg);
  @JsProperty String webkitBorderBeforeWidth();
  @JsProperty HTMLStyle webkitBorderBeforeWidth(String arg);
  @JsProperty String webkitBorderEnd();
  @JsProperty HTMLStyle webkitBorderEnd(String arg);
  @JsProperty String webkitBorderEndColor();
  @JsProperty HTMLStyle webkitBorderEndColor(String arg);
  @JsProperty String webkitBorderEndStyle();
  @JsProperty HTMLStyle webkitBorderEndStyle(String arg);
  @JsProperty String webkitBorderEndWidth();
  @JsProperty HTMLStyle webkitBorderEndWidth(String arg);
  @JsProperty String webkitBorderFit();
  @JsProperty HTMLStyle webkitBorderFit(String arg);
  @JsProperty String webkitBorderHorizontalSpacing();
  @JsProperty HTMLStyle webkitBorderHorizontalSpacing(String arg);
  @JsProperty String webkitBorderImage();
  @JsProperty HTMLStyle webkitBorderImage(String arg);
  @JsProperty String webkitBorderRadius();
  @JsProperty HTMLStyle webkitBorderRadius(String arg);
  @JsProperty String webkitBorderStart();
  @JsProperty HTMLStyle webkitBorderStart(String arg);
  @JsProperty String webkitBorderStartColor();
  @JsProperty HTMLStyle webkitBorderStartColor(String arg);
  @JsProperty String webkitBorderStartStyle();
  @JsProperty HTMLStyle webkitBorderStartStyle(String arg);
  @JsProperty String webkitBorderStartWidth();
  @JsProperty HTMLStyle webkitBorderStartWidth(String arg);
  @JsProperty String webkitBorderVerticalSpacing();
  @JsProperty HTMLStyle webkitBorderVerticalSpacing(String arg);
  @JsProperty String webkitBoxAlign();
  @JsProperty HTMLStyle webkitBoxAlign(String arg);
  @JsProperty String webkitBoxDecorationBreak();
  @JsProperty HTMLStyle webkitBoxDecorationBreak(String arg);
  @JsProperty String webkitBoxDirection();
  @JsProperty HTMLStyle webkitBoxDirection(String arg);
  @JsProperty String webkitBoxFlex();
  @JsProperty HTMLStyle webkitBoxFlex(String arg);
  @JsProperty String webkitBoxFlexGroup();
  @JsProperty HTMLStyle webkitBoxFlexGroup(String arg);
  @JsProperty String webkitBoxLines();
  @JsProperty HTMLStyle webkitBoxLines(String arg);
  @JsProperty String webkitBoxOrdinalGroup();
  @JsProperty HTMLStyle webkitBoxOrdinalGroup(String arg);
  @JsProperty String webkitBoxOrient();
  @JsProperty HTMLStyle webkitBoxOrient(String arg);
  @JsProperty String webkitBoxPack();
  @JsProperty HTMLStyle webkitBoxPack(String arg);
  @JsProperty String webkitBoxReflect();
  @JsProperty HTMLStyle webkitBoxReflect(String arg);
  @JsProperty String webkitBoxShadow();
  @JsProperty HTMLStyle webkitBoxShadow(String arg);
  @JsProperty String webkitClipPath();
  @JsProperty HTMLStyle webkitClipPath(String arg);
  @JsProperty String webkitColumnBreakAfter();
  @JsProperty HTMLStyle webkitColumnBreakAfter(String arg);
  @JsProperty String webkitColumnBreakBefore();
  @JsProperty HTMLStyle webkitColumnBreakBefore(String arg);
  @JsProperty String webkitColumnBreakInside();
  @JsProperty HTMLStyle webkitColumnBreakInside(String arg);
  @JsProperty String webkitColumnCount();
  @JsProperty HTMLStyle webkitColumnCount(String arg);
  @JsProperty String webkitColumnGap();
  @JsProperty HTMLStyle webkitColumnGap(String arg);
  @JsProperty String webkitColumnRule();
  @JsProperty HTMLStyle webkitColumnRule(String arg);
  @JsProperty String webkitColumnRuleColor();
  @JsProperty HTMLStyle webkitColumnRuleColor(String arg);
  @JsProperty String webkitColumnRuleStyle();
  @JsProperty HTMLStyle webkitColumnRuleStyle(String arg);
  @JsProperty String webkitColumnRuleWidth();
  @JsProperty HTMLStyle webkitColumnRuleWidth(String arg);
  @JsProperty String webkitColumnSpan();
  @JsProperty HTMLStyle webkitColumnSpan(String arg);
  @JsProperty String webkitColumnWidth();
  @JsProperty HTMLStyle webkitColumnWidth(String arg);
  @JsProperty String webkitColumns();
  @JsProperty HTMLStyle webkitColumns(String arg);
  @JsProperty String webkitFilter();
  @JsProperty HTMLStyle webkitFilter(String arg);
  @JsProperty String webkitFontFeatureSettings();
  @JsProperty HTMLStyle webkitFontFeatureSettings(String arg);
  @JsProperty String webkitFontSizeDelta();
  @JsProperty HTMLStyle webkitFontSizeDelta(String arg);
  @JsProperty String webkitFontSmoothing();
  @JsProperty HTMLStyle webkitFontSmoothing(String arg);
  @JsProperty String webkitHighlight();
  @JsProperty HTMLStyle webkitHighlight(String arg);
  @JsProperty String webkitHyphenateCharacter();
  @JsProperty HTMLStyle webkitHyphenateCharacter(String arg);
  @JsProperty String webkitLineBoxContain();
  @JsProperty HTMLStyle webkitLineBoxContain(String arg);
  @JsProperty String webkitLineBreak();
  @JsProperty HTMLStyle webkitLineBreak(String arg);
  @JsProperty String webkitLineClamp();
  @JsProperty HTMLStyle webkitLineClamp(String arg);
  @JsProperty String webkitLocale();
  @JsProperty HTMLStyle webkitLocale(String arg);
  @JsProperty String webkitLogicalHeight();
  @JsProperty HTMLStyle webkitLogicalHeight(String arg);
  @JsProperty String webkitLogicalWidth();
  @JsProperty HTMLStyle webkitLogicalWidth(String arg);
  @JsProperty String webkitMarginAfter();
  @JsProperty HTMLStyle webkitMarginAfter(String arg);
  @JsProperty String webkitMarginAfterCollapse();
  @JsProperty HTMLStyle webkitMarginAfterCollapse(String arg);
  @JsProperty String webkitMarginBefore();
  @JsProperty HTMLStyle webkitMarginBefore(String arg);
  @JsProperty String webkitMarginBeforeCollapse();
  @JsProperty HTMLStyle webkitMarginBeforeCollapse(String arg);
  @JsProperty String webkitMarginBottomCollapse();
  @JsProperty HTMLStyle webkitMarginBottomCollapse(String arg);
  @JsProperty String webkitMarginCollapse();
  @JsProperty HTMLStyle webkitMarginCollapse(String arg);
  @JsProperty String webkitMarginEnd();
  @JsProperty HTMLStyle webkitMarginEnd(String arg);
  @JsProperty String webkitMarginStart();
  @JsProperty HTMLStyle webkitMarginStart(String arg);
  @JsProperty String webkitMarginTopCollapse();
  @JsProperty HTMLStyle webkitMarginTopCollapse(String arg);
  @JsProperty String webkitMask();
  @JsProperty HTMLStyle webkitMask(String arg);
  @JsProperty String webkitMaskBoxImage();
  @JsProperty HTMLStyle webkitMaskBoxImage(String arg);
  @JsProperty String webkitMaskBoxImageOutset();
  @JsProperty HTMLStyle webkitMaskBoxImageOutset(String arg);
  @JsProperty String webkitMaskBoxImageRepeat();
  @JsProperty HTMLStyle webkitMaskBoxImageRepeat(String arg);
  @JsProperty String webkitMaskBoxImageSlice();
  @JsProperty HTMLStyle webkitMaskBoxImageSlice(String arg);
  @JsProperty String webkitMaskBoxImageSource();
  @JsProperty HTMLStyle webkitMaskBoxImageSource(String arg);
  @JsProperty String webkitMaskBoxImageWidth();
  @JsProperty HTMLStyle webkitMaskBoxImageWidth(String arg);
  @JsProperty String webkitMaskClip();
  @JsProperty HTMLStyle webkitMaskClip(String arg);
  @JsProperty String webkitMaskComposite();
  @JsProperty HTMLStyle webkitMaskComposite(String arg);
  @JsProperty String webkitMaskImage();
  @JsProperty HTMLStyle webkitMaskImage(String arg);
  @JsProperty String webkitMaskOrigin();
  @JsProperty HTMLStyle webkitMaskOrigin(String arg);
  @JsProperty String webkitMaskPosition();
  @JsProperty HTMLStyle webkitMaskPosition(String arg);
  @JsProperty String webkitMaskPositionX();
  @JsProperty HTMLStyle webkitMaskPositionX(String arg);
  @JsProperty String webkitMaskPositionY();
  @JsProperty HTMLStyle webkitMaskPositionY(String arg);
  @JsProperty String webkitMaskRepeat();
  @JsProperty HTMLStyle webkitMaskRepeat(String arg);
  @JsProperty String webkitMaskRepeatX();
  @JsProperty HTMLStyle webkitMaskRepeatX(String arg);
  @JsProperty String webkitMaskRepeatY();
  @JsProperty HTMLStyle webkitMaskRepeatY(String arg);
  @JsProperty String webkitMaskSize();
  @JsProperty HTMLStyle webkitMaskSize(String arg);
  @JsProperty String webkitMaxLogicalHeight();
  @JsProperty HTMLStyle webkitMaxLogicalHeight(String arg);
  @JsProperty String webkitMaxLogicalWidth();
  @JsProperty HTMLStyle webkitMaxLogicalWidth(String arg);
  @JsProperty String webkitMinLogicalHeight();
  @JsProperty HTMLStyle webkitMinLogicalHeight(String arg);
  @JsProperty String webkitMinLogicalWidth();
  @JsProperty HTMLStyle webkitMinLogicalWidth(String arg);
  @JsProperty String webkitPaddingAfter();
  @JsProperty HTMLStyle webkitPaddingAfter(String arg);
  @JsProperty String webkitPaddingBefore();
  @JsProperty HTMLStyle webkitPaddingBefore(String arg);
  @JsProperty String webkitPaddingEnd();
  @JsProperty HTMLStyle webkitPaddingEnd(String arg);
  @JsProperty String webkitPaddingStart();
  @JsProperty HTMLStyle webkitPaddingStart(String arg);
  @JsProperty String webkitPerspective();
  @JsProperty HTMLStyle webkitPerspective(String arg);
  @JsProperty String webkitPerspectiveOrigin();
  @JsProperty HTMLStyle webkitPerspectiveOrigin(String arg);
  @JsProperty String webkitPerspectiveOriginX();
  @JsProperty HTMLStyle webkitPerspectiveOriginX(String arg);
  @JsProperty String webkitPerspectiveOriginY();
  @JsProperty HTMLStyle webkitPerspectiveOriginY(String arg);
  @JsProperty String webkitPrintColorAdjust();
  @JsProperty HTMLStyle webkitPrintColorAdjust(String arg);
  @JsProperty String webkitRtlOrdering();
  @JsProperty HTMLStyle webkitRtlOrdering(String arg);
  @JsProperty String webkitRubyPosition();
  @JsProperty HTMLStyle webkitRubyPosition(String arg);
  @JsProperty String webkitTapHighlightColor();
  @JsProperty HTMLStyle webkitTapHighlightColor(String arg);
  @JsProperty String webkitTextCombine();
  @JsProperty HTMLStyle webkitTextCombine(String arg);
  @JsProperty String webkitTextDecorationsInEffect();
  @JsProperty HTMLStyle webkitTextDecorationsInEffect(String arg);
  @JsProperty String webkitTextEmphasis();
  @JsProperty HTMLStyle webkitTextEmphasis(String arg);
  @JsProperty String webkitTextEmphasisColor();
  @JsProperty HTMLStyle webkitTextEmphasisColor(String arg);
  @JsProperty String webkitTextEmphasisPosition();
  @JsProperty HTMLStyle webkitTextEmphasisPosition(String arg);
  @JsProperty String webkitTextEmphasisStyle();
  @JsProperty HTMLStyle webkitTextEmphasisStyle(String arg);
  @JsProperty String webkitTextFillColor();
  @JsProperty HTMLStyle webkitTextFillColor(String arg);
  @JsProperty String webkitTextOrientation();
  @JsProperty HTMLStyle webkitTextOrientation(String arg);
  @JsProperty String webkitTextSecurity();
  @JsProperty HTMLStyle webkitTextSecurity(String arg);
  @JsProperty String webkitTextStroke();
  @JsProperty HTMLStyle webkitTextStroke(String arg);
  @JsProperty String webkitTextStrokeColor();
  @JsProperty HTMLStyle webkitTextStrokeColor(String arg);
  @JsProperty String webkitTextStrokeWidth();
  @JsProperty HTMLStyle webkitTextStrokeWidth(String arg);
  @JsProperty String webkitTransform();
  @JsProperty HTMLStyle webkitTransform(String arg);
  @JsProperty String webkitTransformOrigin();
  @JsProperty HTMLStyle webkitTransformOrigin(String arg);
  @JsProperty String webkitTransformOriginX();
  @JsProperty HTMLStyle webkitTransformOriginX(String arg);
  @JsProperty String webkitTransformOriginY();
  @JsProperty HTMLStyle webkitTransformOriginY(String arg);
  @JsProperty String webkitTransformOriginZ();
  @JsProperty HTMLStyle webkitTransformOriginZ(String arg);
  @JsProperty String webkitTransformStyle();
  @JsProperty HTMLStyle webkitTransformStyle(String arg);
  @JsProperty String webkitTransition();
  @JsProperty HTMLStyle webkitTransition(String arg);
  @JsProperty String webkitTransitionDelay();
  @JsProperty HTMLStyle webkitTransitionDelay(String arg);
  @JsProperty String webkitTransitionDuration();
  @JsProperty HTMLStyle webkitTransitionDuration(String arg);
  @JsProperty String webkitTransitionProperty();
  @JsProperty HTMLStyle webkitTransitionProperty(String arg);
  @JsProperty String webkitTransitionTimingFunction();
  @JsProperty HTMLStyle webkitTransitionTimingFunction(String arg);
  @JsProperty String webkitUserDrag();
  @JsProperty HTMLStyle webkitUserDrag(String arg);
  @JsProperty String webkitUserModify();
  @JsProperty HTMLStyle webkitUserModify(String arg);
  @JsProperty String webkitUserSelect();
  @JsProperty HTMLStyle webkitUserSelect(String arg);
  @JsProperty String webkitWritingMode();
  @JsProperty HTMLStyle webkitWritingMode(String arg);
  @JsProperty String whiteSpace();
  @JsProperty HTMLStyle whiteSpace(String arg);
  @JsProperty String widows();
  @JsProperty HTMLStyle widows(String arg);
  @JsProperty String width();
  @JsProperty HTMLStyle width(String arg);
  @JsProperty String willChange();
  @JsProperty HTMLStyle willChange(String arg);
  @JsProperty String wordBreak();
  @JsProperty HTMLStyle wordBreak(String arg);
  @JsProperty String wordSpacing();
  @JsProperty HTMLStyle wordSpacing(String arg);
  @JsProperty String wordWrap();
  @JsProperty HTMLStyle wordWrap(String arg);
  @JsProperty String writingMode();
  @JsProperty HTMLStyle writingMode(String arg);
  @JsProperty String zIndex();
  @JsProperty HTMLStyle zIndex(String arg);
  @JsProperty String zoom();
  @JsProperty HTMLStyle zoom(String arg);

}
