#!/usr/bin/perl
#
# Script to generate an interface with all style properties.
#
# To get all attributes of CSSStyleDeclaration run this in JS console:
# > for (i in document.createElement("div").style) console.log(i)
# and paste the list in this script.
#
use strict;

my $attrs='
cssText
alignContent
alignItems
alignSelf
alignmentBaseline
backfaceVisibility
background
backgroundAttachment
backgroundBlendMode
backgroundClip
backgroundColor
backgroundImage
backgroundOrigin
backgroundPosition
backgroundPositionX
backgroundPositionY
backgroundRepeat
backgroundRepeatX
backgroundRepeatY
backgroundSize
baselineShift
border
borderBottom
borderBottomColor
borderBottomLeftRadius
borderBottomRightRadius
borderBottomStyle
borderBottomWidth
borderCollapse
borderColor
borderImage
borderImageOutset
borderImageRepeat
borderImageSlice
borderImageSource
borderImageWidth
borderLeft
borderLeftColor
borderLeftStyle
borderLeftWidth
borderRadius
borderRight
borderRightColor
borderRightStyle
borderRightWidth
borderSpacing
borderStyle
borderTop
borderTopColor
borderTopLeftRadius
borderTopRightRadius
borderTopStyle
borderTopWidth
borderWidth
bottom
boxShadow
boxSizing
bufferedRendering
captionSide
clear
clip
clipPath
clipRule
color
colorInterpolation
colorInterpolationFilters
colorRendering
content
counterIncrement
counterReset
cursor
direction
display
dominantBaseline
emptyCells
enableBackground
fill
fillOpacity
fillRule
filter
flex
flexBasis
flexDirection
flexFlow
flexGrow
flexShrink
flexWrap
float
floodColor
floodOpacity
font
fontFamily
fontKerning
fontSize
fontStretch
fontStyle
fontVariant
fontVariantLigatures
fontWeight
glyphOrientationHorizontal
glyphOrientationVertical
height
imageRendering
justifyContent
left
letterSpacing
lightingColor
lineHeight
listStyle
listStyleImage
listStylePosition
listStyleType
margin
marginBottom
marginLeft
marginRight
marginTop
marker
markerEnd
markerMid
markerStart
mask
maskType
maxHeight
maxWidth
maxZoom
minHeight
minWidth
minZoom
objectFit
objectPosition
opacity
order
orientation
orphans
outline
outlineColor
outlineOffset
outlineStyle
outlineWidth
overflow
overflowWrap
overflowX
overflowY
padding
paddingBottom
paddingLeft
paddingRight
paddingTop
page
pageBreakAfter
pageBreakBefore
pageBreakInside
paintOrder
perspective
perspectiveOrigin
pointerEvents
position
quotes
resize
right
shapeImageThreshold
shapeMargin
shapeOutside
shapeRendering
size
speak
src
stopColor
stopOpacity
stroke
strokeDasharray
strokeDashoffset
strokeLinecap
strokeLinejoin
strokeMiterlimit
strokeOpacity
strokeWidth
tabSize
tableLayout
textAlign
textAnchor
textDecoration
textIndent
textLineThroughColor
textLineThroughMode
textLineThroughStyle
textLineThroughWidth
textOverflow
textOverlineColor
textOverlineMode
textOverlineStyle
textOverlineWidth
textRendering
textShadow
textTransform
textUnderlineColor
textUnderlineMode
textUnderlineStyle
textUnderlineWidth
top
touchAction
transform
transformOrigin
transformStyle
transition
transitionDelay
transitionDuration
transitionProperty
transitionTimingFunction
unicodeBidi
unicodeRange
userZoom
vectorEffect
verticalAlign
visibility
webkitAnimation
webkitAnimationDelay
webkitAnimationDirection
webkitAnimationDuration
webkitAnimationFillMode
webkitAnimationIterationCount
webkitAnimationName
webkitAnimationPlayState
webkitAnimationTimingFunction
webkitAppRegion
webkitAppearance
webkitAspectRatio
webkitBackfaceVisibility
webkitBackgroundClip
webkitBackgroundComposite
webkitBackgroundOrigin
webkitBackgroundSize
webkitBorderAfter
webkitBorderAfterColor
webkitBorderAfterStyle
webkitBorderAfterWidth
webkitBorderBefore
webkitBorderBeforeColor
webkitBorderBeforeStyle
webkitBorderBeforeWidth
webkitBorderEnd
webkitBorderEndColor
webkitBorderEndStyle
webkitBorderEndWidth
webkitBorderFit
webkitBorderHorizontalSpacing
webkitBorderImage
webkitBorderRadius
webkitBorderStart
webkitBorderStartColor
webkitBorderStartStyle
webkitBorderStartWidth
webkitBorderVerticalSpacing
webkitBoxAlign
webkitBoxDecorationBreak
webkitBoxDirection
webkitBoxFlex
webkitBoxFlexGroup
webkitBoxLines
webkitBoxOrdinalGroup
webkitBoxOrient
webkitBoxPack
webkitBoxReflect
webkitBoxShadow
webkitClipPath
webkitColumnBreakAfter
webkitColumnBreakBefore
webkitColumnBreakInside
webkitColumnCount
webkitColumnGap
webkitColumnRule
webkitColumnRuleColor
webkitColumnRuleStyle
webkitColumnRuleWidth
webkitColumnSpan
webkitColumnWidth
webkitColumns
webkitFilter
webkitFontFeatureSettings
webkitFontSizeDelta
webkitFontSmoothing
webkitHighlight
webkitHyphenateCharacter
webkitLineBoxContain
webkitLineBreak
webkitLineClamp
webkitLocale
webkitLogicalHeight
webkitLogicalWidth
webkitMarginAfter
webkitMarginAfterCollapse
webkitMarginBefore
webkitMarginBeforeCollapse
webkitMarginBottomCollapse
webkitMarginCollapse
webkitMarginEnd
webkitMarginStart
webkitMarginTopCollapse
webkitMask
webkitMaskBoxImage
webkitMaskBoxImageOutset
webkitMaskBoxImageRepeat
webkitMaskBoxImageSlice
webkitMaskBoxImageSource
webkitMaskBoxImageWidth
webkitMaskClip
webkitMaskComposite
webkitMaskImage
webkitMaskOrigin
webkitMaskPosition
webkitMaskPositionX
webkitMaskPositionY
webkitMaskRepeat
webkitMaskRepeatX
webkitMaskRepeatY
webkitMaskSize
webkitMaxLogicalHeight
webkitMaxLogicalWidth
webkitMinLogicalHeight
webkitMinLogicalWidth
webkitPaddingAfter
webkitPaddingBefore
webkitPaddingEnd
webkitPaddingStart
webkitPerspective
webkitPerspectiveOrigin
webkitPerspectiveOriginX
webkitPerspectiveOriginY
webkitPrintColorAdjust
webkitRtlOrdering
webkitRubyPosition
webkitTapHighlightColor
webkitTextCombine
webkitTextDecorationsInEffect
webkitTextEmphasis
webkitTextEmphasisColor
webkitTextEmphasisPosition
webkitTextEmphasisStyle
webkitTextFillColor
webkitTextOrientation
webkitTextSecurity
webkitTextStroke
webkitTextStrokeColor
webkitTextStrokeWidth
webkitTransform
webkitTransformOrigin
webkitTransformOriginX
webkitTransformOriginY
webkitTransformOriginZ
webkitTransformStyle
webkitTransition
webkitTransitionDelay
webkitTransitionDuration
webkitTransitionProperty
webkitTransitionTimingFunction
webkitUserDrag
webkitUserModify
webkitUserSelect
webkitWritingMode
whiteSpace
widows
width
willChange
wordBreak
wordSpacing
wordWrap
writingMode
zIndex
zoom
getPropertyValue
removeProperty
getPropertyPriority
setProperty
item
getPropertyCSSValue
';

my $head='
package com.vaadin.prototype.wc.gwt.client.html;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.js.JsProperty;
import com.google.gwt.core.client.js.JsType;

@JsType(prototype = "CSSStyleDeclaration", isNative = true)
public interface HTMLStyle {
  String getPropertyValue();
  int getPropertyPriority();
  void setProperty(String prop, String val);
  void removeProperty(String prop);
  JavaScriptObject getPropertyCSSValue();
';

my $body = "";

foreach my $a (split(/\s+/, $attrs)) {
  if ($a !~ /^(get|set|remove|item)/ && $a ne '') {
    $a = "${a}_" if ($a =~ /(float)/);
    $body .=  "  \@JsProperty String $a();\n";
    $body .=  "  \@JsProperty HTMLStyle $a(String arg);\n";
  }
}

print "Generated HTMLStyle.java\n";
open(my $f, ">HTMLStyle.java");
print $f "$head$body\n}\n";
close($f);
