/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/vaadin-grid-filter-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

export {FilterMixin};

declare function FilterMixin<T extends new (...args: any[]) => {}>(base: T): T & FilterMixinConstructor;

interface FilterMixinConstructor {
  new(...args: any[]): FilterMixin;
}

export {FilterMixinConstructor};

interface FilterMixin {
  ready(): void;
  _mapFilters(): GridFilter[];
}

import {GridFilter} from '../@types/interfaces';
