/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/vaadin-grid-column-resizing-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {GestureEventListeners} from '@polymer/polymer/lib/mixins/gesture-event-listeners.js';

import {addListener} from '@polymer/polymer/lib/utils/gestures.js';

export {ColumnResizingMixin};

declare function ColumnResizingMixin<T extends new (...args: any[]) => {}>(base: T): T & ColumnResizingMixinConstructor;

interface ColumnResizingMixinConstructor {
  new(...args: any[]): ColumnResizingMixin;
}

export {ColumnResizingMixinConstructor};

interface ColumnResizingMixin {
  ready(): void;
}
